"use client";
import React, { useEffect, useState } from "react";
import BarcodeScanner from "@/components/BarcodeScanner";
import { TextResult } from "dynamsoft-javascript-barcode";
import Head from "next/head";
import { Button } from "@/components/ui/button";
import useScanner from "../hooks/scanner/StaticHooks/useScanner";

async function fetchLicense() {
  let license: string | undefined = process.env.DBRLicense;
  if (license === undefined) {
    license = "";
  }
  return license;
}

export default function Home() {
  const { closeScanner, onScanned, toggleScanning, openScanner } = useScanner();
  const [initialized, setInitialized] = useState(false);
  const [license, setLicense] = useState<string>("");

  useEffect(() => {
    const loadLicense = async () => {
      const fetchedLicense = await fetchLicense();
      setLicense(fetchedLicense);
    };
    loadLicense();
  }, []);

  return (
    <>
      <Head>
        <title>Next.js Barcode Scanner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="app">
          <h2>Next.js Barcode Scanner</h2>
          {initialized ? (
            <>
              <Button onClick={toggleScanning} variant="primary">
                {openScanner ? "Stop Scanning" : "Start Scanning"}
              </Button>
            </>
          ) : (
            <div>Initializing...</div>
          )}
          <div className="barcodeScanner">
            <BarcodeScanner
              license={license}
              onInitialized={() => setInitialized(true)}
              isActive={openScanner}
              onScanned={(results) => onScanned(results)}
              onClose={closeScanner} // Pass onClose function here
            ></BarcodeScanner>
          </div>
        </div>
      </main>
    </>
  );
}
